### ISSUE TITLE
WordBreaking.java  - code needs fix

### ISSUE THREAD

**Issue by kbprakash** [epibook/epibook.github.io#12]
https://github.com/epibook/epibook.github.io/blob/master/solutions/java/src/main/java/com/epi/WordBreaking.java#L30-L31

logic is broken with valid input

```java
String target = "bedbathandbeyond";
    dictionary.add("bed");
   // dictionary.add("bat");
    dictionary.add("bath");
    dictionary.add("and");
    dictionary.add("hand");
    dictionary.add("beyond");
```

**Comment by tsunghsienlee** [comment]
Hey @kbprakash,

Many thanks for your report, and the code is fixed at https://github.com/epibook/epibook.github.io/blob/master/solutions/java/src/main/java/com/epi/WordBreaking.java.  You can take a look of that, and I add a test case like yours also.
