### ISSUE TITLE
Finding_min_max.cc needs a fix.

### ISSUE THREAD

**Issue by Astellar** [epibook/epibook.github.io#14]
```C++
if (A.size() <= 1) {
  return {A.front(), A.front()};
}
```
If `A` is empty, accessing `A.front()` leads to undefined behaviour. As we return elements themselves instead of iterators, may be throwing an exception when `A.empty() == true` is sufficient for this exercise.

**Comment by tsunghsienlee** [comment]
Hey @Astellar,

Thanks for your report, and you suggestion makes sense.  However, this kind of problem is something we called invalid input which is not the main focus of this problem.  Of course in interview you should always try to clarify that with the interviewer.  However, it will district people's focus if we need to handle such invalid input always.  For example, for all binary tree problem, you definitely don't want to deal with the input which is a graph but not a binary tree.

Please let me know if you have any problem.
