### ISSUE TITLE
TestAll.java causing compilation errors

### ISSUE THREAD

**Issue by kbprakash** [epibook/epibook.github.io#9]
run  mvn clean install. you will see lot of compilation errors causing from TestAll.java
Please fix the compilation errors in TestAll.java

**Comment by tsunghsienlee** [comment]
Hey Bhanu,

The TesAll.java is fixed now.  Thanks for your report.

**Comment by kbprakash** [comment]
you just removed the pom.xml. Thats not a fix and without that how do you plan to specify the dependent jars needed for TestAll.java ?

**Comment by tsunghsienlee** [comment]
Hey Bhanu,

Thanks for your report, could you try that again?

**Comment by kbprakash** [comment]
Looks good. Thanks @tsunghsienlee
